services:

  producer:
    build:
      context: .
    command: go run /src/example/cmd/producer/main.go
    volumes:
      - .:/src:cached
      - go:/go
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - default

  worker:
    build:
      context: .
    command: go run /src/example/cmd/worker/main.go
    volumes:
      - .:/src:cached
      - go:/go
    environment:
      GOMAXPROCS: 2
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - default

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init.sh:/etc/localstack/init/ready.d/init-aws.sh
    environment:
      - SERVICES=sqs
      - DEBUG=0
      - LS_LOG=error
    healthcheck:
      test: awslocal sqs list-queues
      interval: 2s
      start_period: 20s
      retries: 30
      timeout: 30s
    networks:
      - default

volumes:
  go:
