services:
  producer:
    build:
      context: .
    environment:
      - REDIS_URL=redis://:password@redis:6379/0
    command: go run /src/example/cmd/producer/main.go
    volumes:
      - .:/src:cached
      - go:/go
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - default

  worker:
    build:
      context: .
    environment:
      - REDIS_URL=redis://:password@redis:6379/0
    command: go run /src/example/cmd/worker/main.go
    volumes:
      - .:/src:cached
      - go:/go
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - default

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init.sh:/etc/localstack/init/ready.d/init-aws.sh
    environment:
      - SERVICES=sqs
      - DEBUG=0
      - LS_LOG=error
    healthcheck:
      test: awslocal sqs list-queues
      interval: 2s
      start_period: 20s
      retries: 30
      timeout: 30s
    networks:
      - default

  redis:
    image: redis:7.4.1-alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
    command: ["redis-server", "--requirepass", "password"]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      default:

volumes:
  go:
  redis:
